databases:
  - name: app-cafet-db
    plan: free

services:
  - type: web
    name: app-cafet-api
    runtime: docker
    dockerfilePath: cafeteria-backend/Dockerfile
    dockerContext: cafeteria-backend
    plan: free
    healthCheckPath: /api/auth/users
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "false"
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: app-cafet-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: app-cafet-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: app-cafet-db
          property: password
